# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/brigade/overcommit/blob/master/config/default.yml
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/brigade/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/brigade/overcommit#configuration
#

PreCommit:
  #ALL:
  #  exclude:
  #    - "thirdparty/xxx/**/*"
  #    - "thirdparty/yyy/**/*"

  TrailingWhitespace:
    enabled: true

  HardTabs:
    enabled: true
    exclude:
      - develop/vssln/scattercc.sln
      - thirdparty/**/*.cpp
      - thirdparty/**/*.hpp
      - thirdparty/**/*.h

  LineEndings:
    enabled: true
    exclude:
      - develop/vssln/scattercc.sln
      - develop/vssln/*/*.vcxproj
      - develop/vssln/*/*.vcxproj.filters
      - develop/vssln/*/*.vcxitems
      - develop/vssln/*/*.vcxitems.filters
      - thirdparty/**/*.cpp
      - thirdparty/**/*.hpp
      - thirdparty/**/*.h
    eol: "\n"

  ExecutePermissions:
    enabled: true
    exclude:
      - ci/**/*.sh
      - develop/ci/*.sh
      - develop/ci/*.py

  # Custom hooks for scattercc
  CppHeaderIncludeOnceGuard:
    enabled: true
    description: 'Check C++ header files include-once guard'
    include:
      - '**/*.hpp'
      - '**/*.h'
    exclude:
      #- thirdparty/**/*.cpp  # not included at all
      - thirdparty/**/*.hpp
      - thirdparty/**/*.h

CommitMsg:
  CapitalizedSubject:
    enabled: true

  HardTabs:
    enabled: true

  SingleLineSubject:
    enabled: true

  TrailingPeriod:
    enabled: true

  TextWidth:
    enabled: false
